version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: azure_costs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: azure_costs
      MYSQL_USER: azure
      MYSQL_PASSWORD: azurepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  importer:
    build: .
    container_name: azure_cost_importer
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: azure
      MYSQL_PASSWORD: azurepassword
      MYSQL_DATABASE: azure_costs
      CSV_FILE_PATH: "/data/azure_costs.csv"
    volumes:
      - ./data:/data

volumes:
  mysql_data: